# Generated by Django 4.2 on 2026-05-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('pokemons', models.ManyToManyField(blank=True, related_name='trainers', to='pokedex.pokemon')),
            ],
        ),
    ]
