# Generated by Django 6.0.5 on 2026-05-07 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='pokemons',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_photos/'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemons', to='pokedex.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Fuego', 'Fuego'), ('Agua', 'Agua'), ('Planta', 'Planta'), ('Eléctrico', 'Eléctrico'), ('Normal', 'Normal'), ('Psíquico', 'Psíquico'), ('Hielo', 'Hielo'), ('Lucha', 'Lucha'), ('Veneno', 'Veneno'), ('Tierra', 'Tierra'), ('Volador', 'Volador'), ('Bicho', 'Bicho'), ('Roca', 'Roca'), ('Fantasma', 'Fantasma'), ('Dragón', 'Dragón')], max_length=50),
        ),
    ]
